#!/usr/bin/env bash

# todo: add more descriptive function names
# http://www.kfirlavi.com/blog/2012/11/14/defensive-bash-programming/
lpass status > /dev/null || exit 1
lpass show --notes ubuntu-workstation
